### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by singulared**
Fixed HMAC initialization for using in Python3.
Fix tests.

### CODE REVIEW

**Comment by Phillipmartin** [comment]
Thanks! I'll take a look and get hopefully merge this week

**Comment by singulared** [comment]
Thanks a lot!

**Comment by singulared** [comment]
What do you think about it?

**Comment by Phillipmartin** [comment]
yup, I am actually re-factoring my build environment, so I'll update PyPi in the new year.

**Comment by singulared** [comment]
Thanks a lot!

**Pull request merged**
